name: Delete Old Tags

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:

jobs:
  delete-old-tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Delete tags older than 90 days
      run: |
        # 获取90天前的日期
        CUTOFF_DATE=$(date -d "16 days ago" +%Y-%m-%d)
        
        # 列出所有tags并过滤
        git for-each-ref --sort=-creatordate --format '%(creatordate:iso8601) %(refname:short)' refs/tags | \
        while read -r datetime timezone tag; do
          # 提取日期部分 (YYYY-MM-DD)
          date=${datetime%%T*}
          if [[ "$date" < "$CUTOFF_DATE" ]]; then
            echo "Deleting old tag: $tag ($date)"
            git tag -d "$tag"
            git push origin ":refs/tags/$tag"
          fi
        done
