name: Cleanup Old Releases

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old releases
        uses: actions/delete-release@v1
        with:
          delete_tag: true  # 同时删除关联的标签
          keep_latest: 5    # 保留最新的5个发布
          repo: ${{ github.repository }}
          token: ${{ secrets.GI_TOKEN }}
