name: Cleanup Old Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'  # 每周日午夜运行

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1  # 保留最新的5个发布
          delete_tag: true  # 同时删除关联的标签
          repo: ${{ github.repository }}
          token: ${{ secrets.GI_TOKEN }}
        env:
         GITHUB_TOKEN: ${{ secrets.GI_TOKEN }}
